// app/components/week/InfoBanner.tsx
import {
  getDescriptionForEventType,
  getItemForEventType,
} from "~/utils/calendarEventUtils";
import type { TransformedCalendarEvent } from "~/utils/transformCalendarEvents";

interface Props {
  event: TransformedCalendarEvent;
}

export function InfoBanner({ event }: Props) {
  const symbol = getItemForEventType(event.type);

  let text = "";

  if (event.duration == "HalfDay") {
    text = "½ Day: ";
  }

  text += getDescriptionForEventType(event.type);

  return (
    <div
      data-testid={event.type}
      className="flex w-full items-center justify-start rounded-lg bg-blue-600 p-4"
    >
      <span className="material-symbols-outlined mr-2 text-white">
        {symbol}
      </span>
      <p className="text-sm text-white">{text}</p>
    </div>
  );
}

// src/lib/components/InfoBanner.svelte
<script>
    export let text;
    export let symbol;
    export let testId = "";
</script>

<div
    data-testid={testId}
    class="flex w-full items-center justify-start rounded-lg bg-blue-600 p-4"
>
    <span class="material-symbols-outlined mr-2 text-white">
        {symbol}
    </span>
    <p class="text-sm text-white">
        {text}
    </p>
</div>
